server:
  port: 8200

management:
  endpoints:
    web:
      exposure:
        # 这里用* 代表暴露所有端点只是为了观察效果，实际中按照需进行端点暴露
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      # 详细信息显示给所有用户。
      show-details: always
  health:
    status:
      http-mapping:
        # 自定义健康检查返回状态码对应的http状态码
        FATAL:  503
    
spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type:  text/html
    
  application:
    name: fca-alfa-manage
  cloud:
    discovery:
      client:
        simple:
          local:
            service-id: fca-alfa-manage  
  security:
    user:
      name: admin
      password: 12345
  session:
    store-type: redis
  redis:
    database: 0
    host: 192.168.1.199
    port: 6379
    password: 123456
    jedis:
      pool:
       max-idle: 200
       max-active: 200
       max-wait: -1
       min-idle: 0
    timeout: 10000 
  datasource:
    name: test
    #url: jdbc:mysql://127.0.0.1:3306/scfl?autoReconnect=true&characterEncoding=UTF-8
    #username: root
    #password: 123456
    url: jdbc:mysql://192.168.1.199:3306/fca_alfa?autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


# eureka:
# client:
#    serviceUrl:
#      defaultZone : http://admin:12345@eurekaServer1.com:8000/eureka,http://admin:12345@eurekaServer2.com:8001/eureka
      
mybatis:
  config-location: /com/fca/alfa/mapper/*.xml

logging:
  config: classpath:logback-spring.xml
  level:
    -com.fca.alfa.mapper: DEBUG
    -com.fca.alfa: INFO 
    #root: INFO